### ISSUE TITLE
xengsort unclassified.fq.gz missing

### ISSUE THREAD

**Issue by ctman1025** [istrope/Xenomake#7]
Thank you for developing xenomake.  When I analyzed the test dataset provided.  The code stopped at the step of xengsort. The error is because of a missing file, i.e. unclassified.fq.gz.  Does anyone encounter the same issue? I tried to increase the latency, but it didn't help. Below is the error message.  

Waiting at most 5 seconds for missing files.
MissingOutputException in line 99 of /home/ctman/Xenomake/snakemake/xengsort.smk:
Job Missing files after 5 seconds:
/home/ctman/Xenomake-out/test/xengsort/test-unclassified.fq.gz
This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait.
Job id: 14 completed successfully, but some output files are missing. 14
  File "/home/ctman/miniconda3/envs/xenomake/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 584, in handle_job_success
  File "/home/ctman/miniconda3/envs/xenomake/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 252, in handle_job_success

**Comment by istrope** [comment]
thank you for bringing this to my attention, I have updated the file called snakemake/xengsort.smk to fix this problem.

**Comment by ctman1025** [comment]
Hi Shawn,

 

Thank you for getting back to me.  I would also like to ask if there is a way that we can use xenomake to analyze regular 10X scRNAseq data, which does not have spatial information.  This will be very helpful for our project.

 

Thanks again!

 

Best,

Chris

**Comment by istrope** [comment]
yes, I am currently working on an update to Xenomake that will be released by the end of next week. This would extend support to 10x single-cell projects and more spatial array-based platforms.

Best,
Ivy Strope
________________________________

**Comment by ctman1025** [comment]
Hi Ivy,

 

This is awesome. Thank you for your work for the community.  If you have an early version with regular 10X scRNAseq capability, I would like to give a try on our data and perhaps give you some feedback.

 

Please let me know.

 

Best,

Chris

**Comment by istrope** [comment]
I will let you know when I have an updated branch on Github ready for testing. Having someone to help find bugs would be wonderful. Thank you very much

Best,
Ivy
________________________________

**Comment by ctman1025** [comment]
You bet. Thank you!  Please keep me posted. Have a nice day!
